import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Link from "next/link";
import { repo } from "@/lib/db";
import { CampaignBoard } from "@/components/campaign-board";
import { Logo } from "@/components/logo";
import { ThemeToggle } from "@/components/theme-toggle";
import { CopyLink } from "@/components/copy-link";
import { Badge } from "@/components/ui";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

type Props = { params: Promise<{ slug: string }> };

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params;
  const campaign = repo.getCampaignBySlug(slug);
  if (!campaign) return { title: "Campaign not found" };

  const ogImage = campaign.days[0]
    ? `/api/creative/${campaign.days[0].id}.png?og=1`
    : undefined;
  const title = `${campaign.restaurant_name} — ${campaign.month} deals`;
  const description = `A 30-day flash-deal plan: ${campaign.projected_redemptions.toLocaleString()} projected redemptions, ${new Intl.NumberFormat(
    "en-US",
    { style: "currency", currency: "USD", maximumFractionDigits: 0 }
  ).format(campaign.projected_revenue)} projected incremental revenue. Generated by Got60.`;

  return {
    title,
    description,
    openGraph: {
      title,
      description,
      type: "website",
      images: ogImage ? [{ url: ogImage, width: 1200, height: 630 }] : undefined,
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: ogImage ? [ogImage] : undefined,
    },
  };
}

export default async function PublicCampaignPage({ params }: Props) {
  const { slug } = await params;
  const campaign = repo.getCampaignBySlug(slug);
  if (!campaign) notFound();

  const brandColor = campaign.brand?.primary_color || "#f75410";

  return (
    <div className="min-h-screen">
      {/* brand accent bar */}
      <div className="h-1.5 w-full" style={{ background: `linear-gradient(90deg, ${brandColor}, ${brandColor}88)` }} />

      <header className="border-b border-border">
        <div className="mx-auto flex max-w-7xl flex-wrap items-center gap-3 px-4 py-4 sm:px-6 lg:px-8">
          <div className="flex items-center gap-3">
            {campaign.brand?.logo_url ? (
              // eslint-disable-next-line @next/next/no-img-element
              <img
                src={campaign.brand.logo_url}
                alt=""
                className="size-11 rounded-xl border border-border object-cover"
              />
            ) : (
              <div
                className="flex size-11 items-center justify-center rounded-xl text-lg font-bold text-white"
                style={{ background: brandColor }}
              >
                {campaign.restaurant_name.slice(0, 1)}
              </div>
            )}
            <div>
              <h1 className="font-display text-2xl leading-tight sm:text-3xl">
                {campaign.restaurant_name}
              </h1>
              <p className="text-sm text-fg-subtle">
                {campaign.month} · 30-day flash plan
              </p>
            </div>
          </div>
          <div className="ml-auto flex items-center gap-2">
            <Badge tone={campaign.status === "published" ? "mint" : "muted"} className="hidden sm:inline-flex">
              {campaign.status === "published" ? "Published" : "Preview"}
            </Badge>
            <CopyLink label="Share" />
            <ThemeToggle />
          </div>
        </div>
      </header>

      <CampaignBoard initial={campaign} editable />

      <footer className="border-t border-border py-8">
        <div className="mx-auto flex max-w-7xl flex-col items-center gap-2 px-4 text-center sm:px-6 lg:px-8">
          <Logo href="/" />
          <p className="max-w-md text-xs text-fg-subtle text-pretty">
            This campaign was generated by Got60 — a brain that&apos;s been in the kitchen.
            Reads your sales history and live consumer demand to build recurring, on-brand deals.
          </p>
          <Link href="/" className="text-xs font-medium text-ember-600 hover:text-ember-700">
            See how it works →
          </Link>
        </div>
      </footer>
    </div>
  );
}
