import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Link from "next/link";
import { repo } from "@/lib/db";
import { CampaignBoard } from "@/components/campaign-board";
import { getAccountEmail } from "@/lib/billing/account";
import { canView, canEdit, toPublic } from "@/lib/authz";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

type Props = { params: Promise<{ slug: string }> };

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params;
  const campaign = await repo.getCampaignBySlug(slug);
  // Private drafts must not leak their name/numbers into link previews either.
  if (!campaign || !canView(campaign, await getAccountEmail())) return { title: "Campaign not found" };

  const ogImage = campaign.days[0]
    ? `/api/creative/${campaign.days[0].id}.png?og=1`
    : undefined;
  const title = `${campaign.restaurant_name} — ${campaign.month} deals`;
  const description = `A 30-day flash-deal plan: ${campaign.projected_redemptions.toLocaleString()} projected redemptions, ${new Intl.NumberFormat(
    "en-US",
    { style: "currency", currency: "USD", maximumFractionDigits: 0 }
  ).format(campaign.projected_revenue)} projected incremental revenue. Generated by Swell.`;

  return {
    title,
    description,
    openGraph: {
      title,
      description,
      type: "website",
      images: ogImage ? [{ url: ogImage, width: 1200, height: 630 }] : undefined,
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: ogImage ? [ogImage] : undefined,
    },
  };
}

export default async function PublicCampaignPage({ params }: Props) {
  const { slug } = await params;
  const campaign = await repo.getCampaignBySlug(slug);
  const viewer = await getAccountEmail();
  if (!campaign || !canView(campaign, viewer)) notFound();
  // Only the owner gets edit + activate controls; everyone else sees the
  // published artifact read-only.
  const isOwner = canEdit(campaign, viewer);

  // Edge-to-edge Swell OS artifact. The board's own header carries the brand,
  // the /C/slug label, LIVE status, Share and Activate — no outer chrome.
  const footer = (
    <div className="mx-auto flex max-w-[1180px] flex-col items-center gap-2 px-5 py-10 text-center sm:px-10">
      <Link href="/" className="flex items-baseline gap-2">
        <span className="font-display text-lg">Swell</span>
        <span className="font-mono text-[9px] tracking-[0.18em]" style={{ color: "var(--os-amber)" }}>
          OS
        </span>
      </Link>
      <p className="max-w-md text-xs text-fg-subtle text-pretty">
        Generated by Swell — a brain that&apos;s been in the kitchen. Reads your sales history,
        live local conditions and neighborhood demand to build recurring, on-brand deals.
      </p>
      <Link href="/" className="text-xs font-medium" style={{ color: "var(--os-amber)" }}>
        See how it works →
      </Link>
    </div>
  );

  return (
    <CampaignBoard
      initial={toPublic(campaign)}
      editable={isOwner}
      showActivate={isOwner}
      share
      footer={footer}
    />
  );
}
